spring.application.name=customer-service

server.port=8080

spring.mongodb.uri=${DB_URL}

spring.web.error.include-message=never
spring.web.error.include-binding-errors=never
spring.web.error.include-stacktrace=never
spring.web.error.include-exception=false

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
